//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goldStore.Areas.Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commentId { get; set; }
        public Nullable<int> productId { get; set; }
        public string review { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string email { get; set; }
    
        public virtual product product { get; set; }
    }
}
