//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goldStore.Areas.Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.orderDetails = new HashSet<orderDetails>();
        }
    
        public int orderId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<bool> isOther { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> postCode { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> paymentType { get; set; }
        public Nullable<decimal> shipPrice { get; set; }
        public Nullable<decimal> orderPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderDetails> orderDetails { get; set; }
        public virtual user user { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
