//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goldStore.Areas.Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlist
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
